config/routes.rb
Rails.application.routes.draw do
  get 'catalog', to: 'catalog#index'
  root 'catalog#index'

  namespace :gymnastic_rings do
    get '/', action: 'index'

    resources :programs, only: [:index, :show] do
      resources :days, only: [:show]
    end
  end

  namespace :dumbbells do
    get '/', action: 'index'

    resources :programs, only: [:index, :show] do
      resources :days, only: [:show]
    end
  end

  namespace :self_weight do
    get '/', action: 'index'

    resources :programs, only: [:index, :show] do
      resources :days, only: [:show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :exercises
  belongs_to :program
end

app/models/dumbbells_program.rb
class DumbbellsProgram < Program
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :day
  has_many :resources

  def image_tutorial?
    file_name.include?('gif')
  end
end

app/models/gymnastic_rings_program.rb
class GymnasticRingsProgram < Program
end

app/models/image.rb
class Image < Resource
end

app/models/program.rb
class Program < ApplicationRecord
  has_many :days

  def icon
    self.class.name.split('Program').first.underscore + '.svg'
  end
end

app/models/resource.rb
class Resource < ApplicationRecord
  belongs_to :exercise

  def image?
    type == 'Image'
  end

  def video?
    type == 'Video'
  end
end

app/models/self_weight_program.rb
class SelfWeightProgram < Program
end

app/models/video.rb
class Video < Resource
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :program_path, :program_day_path

  def program_class_name
    controller_path.classify.split('::')[0] + 'Program'
  end

  def program_class
    program_class_name.constantize
  end

  def program_path(program_id)
    send((program_class_name.underscore + '_path').to_sym, program_id)
  end

  def program_day_path(program_id, day_id)
    send((program_class_name.underscore + '_day_path').to_sym, program_id, day_id)
  end
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  add_breadcrumb '<i class="fa">&#xf015</i>'.html_safe, :root_path

  def show
    @program = program_class.find(params[:program_id])
    add_breadcrumb @program.name, program_path(@program.id)
    @day = Day.find_by(program_id: params[:program_id], id: params[:id])
    add_breadcrumb @day.name, program_day_path(@program.id, @day.id)
    @exercises = @day.exercises

    render 'days/show'
  end

end

app/controllers/dumbbells/days_controller.rb
class Dumbbells::DaysController < DaysController
  add_breadcrumb 'С гантелями', :dumbbells_programs_path
end

app/controllers/dumbbells/programs_controller.rb
class Dumbbells::ProgramsController < ProgramsController
  add_breadcrumb 'С гантелями', :dumbbells_programs_path
end

app/controllers/gymnastic_rings/days_controller.rb
class GymnasticRings::DaysController < DaysController
  add_breadcrumb 'С кольцами', :gymnastic_rings_programs_path
end

app/controllers/gymnastic_rings/programs_controller.rb
class GymnasticRings::ProgramsController < ProgramsController
  add_breadcrumb 'С кольцами', :gymnastic_rings_programs_path
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  add_breadcrumb '<i class="fa">&#xf015</i>'.html_safe, :root_path

  def index
    @programs = program_class.all

    render 'programs/index'
  end

  def show
    @program = program_class.find(params[:id])
    @days = @program.days
    add_breadcrumb @program.name, program_path(@program.id)

    render 'programs/show'
  end
end

app/controllers/self_weight/days_controller.rb
class SelfWeight::DaysController < DaysController
  add_breadcrumb 'С собственным весом', :self_weight_programs_path
end

app/controllers/self_weight/programs_controller.rb
class SelfWeight::ProgramsController < ProgramsController
  add_breadcrumb 'С собственным весом', :self_weight_programs_path
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/catalog/index.html.haml
#catalog
  %section.about-inner
    .container.py-lg-5.py-md-4.py-sm-4.py-3
      %h2.title.text-center.mb-lg-5.mb-md-4.mb-sm-4.mb-3 Выберите тип тренировки
      .row.agile-service-grid.pt-lg-4.pt-md-4.pt-3
        .button.col-lg-4.col-sm-12.text-center.gap-1
          = link_to dumbbells_programs_path() do
            .white-shadow
              = inline_svg_tag('dumbbells.svg')
              .ser-inner-info
                %h3 С гантелями
        .button.col-lg-4.col-sm-12.text-center.gap-1
          = link_to gymnastic_rings_programs_path() do
            .white-shadow
              = inline_svg_tag('gymnastic_rings.svg')
              .ser-inner-info
                %h3 С кольцами
        .button.col-lg-4.col-sm-12.text-center.gap-1
          = link_to self_weight_programs_path() do
            .white-shadow
              = inline_svg_tag('self_weight.svg')
              .ser-inner-info
                %h3 С собственным весом

app/views/days/show.html.haml
.row.justify-content-center
  .col-xs-12.col-md-8
    - @exercises.each do |exercise|
      .card.mb-4
        - exercise.resources.each do |resource|
          .mb-4
            - if resource.image?
              = image_tag(resource.name, class: 'img-fluid card-img-top')
            - else
              .embed-responsive.embed-responsive-16by9.card-img-top
                %video.embed-responsive-item{controls: '', preload: 'metadata', playsinline: ''}
                  %source{src: resource.name, type: 'video/mp4'}
        .card-body
          %h2.card-title
            = exercise.name
          %p.card-text
            = exercise.desc

app/views/gymnastic_rings/days/show.html.haml
.container.py-lg-5.py-md-4.py-sm-4.py-3
  .row.agile-service-grid.pt-lg-4.pt-md-4.pt-3
  .col-sm-12
    .row.justify-content-center
      %h3
        = @day.name
    - @exercises.each do |exercise|
      .row
        %h4
          = exercise.name
      .row
        %p
          = exercise.desc
      - exercise.resources.each_with_index do |resource, i|
        .row.mb-3
          - if exercise.resources.count > 1
            %p Вариант #{i + 1}
          - if resource.image?
            = image_tag(resource.name, class: 'img-fluid')
          - else
            .embed-responsive.embed-responsive-16by9
              %video.embed-responsive-item{controls: ''}
                %source{src: resource.name, type: 'video/mp4'}

app/views/gymnastic_rings/programs/index.html.haml
#gymnastic_rings
  .container.py-lg-5.py-md-4.py-sm-4.py-3
    .row.agile-service-grid.pt-lg-4.pt-md-4.pt-3
      - @programs.each do |program|
        .col-lg-4.col-sm-12.text-center.gap-1
          .white-shadow
            = link_to inline_svg_tag('sports.svg'), gymnastic_rings_program_path(program.id)
            .ser-inner-info
              %h3
                = program.name

app/views/programs/index.html.haml
#gymnastic_rings
  .container.py-lg-5.py-md-4.py-sm-4.py-3
    .row.agile-service-grid.pt-lg-4.pt-md-4.pt-3
      - @programs.each do |program|
        .button.col-lg-4.col-sm-12.text-center.gap-1
          = link_to program_path(program.id) do
            .white-shadow
              = inline_svg_tag(program.icon)
              .ser-inner-info
                %h3
                  = program.name

app/views/programs/show.html.haml
#gymnastic_rings
  .container.py-lg-5.py-md-4.py-sm-4.py-3
    .row.agile-service-grid.pt-lg-4.pt-md-4.pt-3
      - @days.each do |day|
        .button.col-lg-4.col-sm-12.text-center.gap-1.mb-4
          = link_to program_day_path(@program.id, day.id) do
            .white-shadow
              = inline_svg_tag('calendar.svg')
              .ser-inner-info
                %h4
                  = day.name

app/views/self_weight/programs/show.html.haml
#gymnastic_rings
  .container.py-lg-5.py-md-4.py-sm-4.py-3
    .row.agile-service-grid.pt-lg-4.pt-md-4.pt-3
      - @days.each do |day|
        .col-lg-4.col-sm-12.text-center.gap-1.mb-4
          .white-shadow
            = link_to inline_svg_tag('calendar.svg'), self_weight_program_day_path(program_id: @program.id, id: day.id)
            .ser-inner-info
              %h4
                = day.name